version: '3.8'

services:
  spacy-app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: spacy-app
    stdin_open: true
    tty: true
    volumes:
      - ../src:/usr/src/app/src
    working_dir: /usr/src/app/src